theme: jekyll-theme-cayman
title: Prateek Pattanaik
Student. I research into the culture of Odisha through stories and songs 
to better understand my roots, and try to add to its digital existence 
through Wikipedia & other projects.
